# MODULARIZAÇÃO

# SURGIU NO INICIO DA DÉCADA DE 60

# SISTEMAS DE FICANDO CADA VEZ MAIORES

# FOCO: DIVIDIR UM PROGRAMA GRANDE

# FOCO: AUMENTAR A LEGIBILIDADE

# FOCO: FACILITAR A MANUTENÇÃO

# BASICAMENTE DIVIDIR O CÓDIGO EM VARIOS ARQUIVOS PARA TER
# FACIL LEITURA E MANUTENÇÃO

# VANTAGENS

# ORGANIZAÇÃO DO CÓDIGO

# FACILIDADE NA MANUTENÇÃO

# OCULTAÇÃO DE CÓDIGO DETANHADO

# REUITILIZAÇÃO EM OUTROS PROJETOS

