a = input('Digite Algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaço? ', a.isspace())
print('È numero? ', a.isnumeric())
print('É alfabético', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em mausculas? ', a.isupper())
print('Está em minusculas? ', a.islower())
print('Está Captalizada? ', a.istitle())
